dekorate.kubernetes.name=apt-demo
dekorate.kubernetes.namespace=default

dekorate.kubernetes.image=quay.io/myorg/apt-demo:1.0

dekorate.kubernetes.labels.env=prod
dekorate.kubernetes.labels.team=backend
dekorate.kubernetes.labels.version=1.0

dekorate.kubernetes.annotations.description=APT demo application
