<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.dekorate</groupId>
    <artifactId>dekorate-2</artifactId>
    <version>999-SNAPSHOT</version>
  </parent>

  <artifactId>dekorate-2-core</artifactId>
  <name>Dekorate :: Dekorate 2 :: Core</name>
  <description>Core interfaces, SPI, and session management</description>

  <dependencies>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-client-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging</artifactId>
    </dependency>
  </dependencies>
</project>
