source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-asciidoc"
  gem "jekyll-paginate-v2"
  gem "jekyll-archives"
  gem "jekyll-seo-tag", "~> 2.8"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "webrick", "~> 1.8"
