dekorate.kubernetes.name=my-app
dekorate.kubernetes.namespace=default

dekorate.kubernetes.image=quay.io/myorg/myapp:1.0

dekorate.kubernetes.labels.env=prod
dekorate.kubernetes.labels.team=backend
dekorate.kubernetes.labels.version=1.0

dekorate.kubernetes.annotations.description=My application

dekorate.kubernetes.replicas=3
